keys:
  - &lagos age1ma4t03shtknsqrr48dw3djsuz692z73axzh0z6e38myh3t8rgyrqlrd4z3
  - &shanghai age15r9skq3lk306hdj4m284hhgm94yywe25dhdan0w6mud558rwquasfn0gz7
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *lagos
      - *shanghai
  - path_regex: shanghai/secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *lagos
      - *shanghai
